export const MESSAGES = {
  ADD_TILE_SUCCESS_MESSAGE: 'Added tile to dashboard successfully',
  EDIT_TILE_SUCCESS_MESSAGE: 'Edited dashboard tile successfully',
  REMOVED_TILE_SUCCESS_MESSAGE: 'Removed tile from dashboard successfully',
  SAVE_CHANGES_SUCCESS_MESSAGE: 'Saved changes successfully',
  GOOGLE_SYNC_ENABLE_MESSAGE: 'Google Calendar sync is enabled for this event',
  CONTENT_DELETED: 'Content deleted',
  RESPONSE_RECORDED_MESSAGE: 'Your response has been successfully recorded',
  UPDATE_EVENT_MESSAGE: "Updated event successfully - it's published",
  ITEM_MOVED_MESSAGE: 'Moved 1 item successfully',
  INTEGRATION_UPDATE_SUCCESS: 'Integration update successful',
  GOOGLE_CALENDAR_CONNECT_SUCCESS_MESSAGE: 'Connected to Google Calendar successfully',
  SCHEDULERS_RAN_SUCCESS: 'Schedulers ran successfully',
  SUCCESS_SCHEDULER_MESSAGE: 'Schedulers ran successfully',
  SUCCESS_SCHEDULER_MESSAGE_ODIN: 'Scheduler ran successfully',
  INTEGRATION_DELETION_MESSAGE: 'Integration deleted',
  DISCONNECT_GOOGLE_SUCCESS_MESSAGE: 'Disconnected Google successfully',
  GOOGLE_ACCOUNT_CONNECTION_MESSAGE: 'Please connect your Google admin account.',
  AZURE_ACCOUNT_CONNECTION_MESSAGE: 'Please connect your Azure admin account to sync.',
  CONNECT_AZURE_SYNC_SUCCESS_MESSAGE: 'Connected to Azure User Sync successfully',
  GOOGLE_CONNECTION_SUCCESS_MESSAGE: 'Connected to Google successfully',
  MULTIPLE_SHARED_DRIVE_ERROR_MESSAGE:
    'Only one shared drive can be linked to a site. To link a different shared drive to this site, the existing drive must be unlinked first.',
  FILE_PREVIEW_ERROR_MESSAGE: 'Unable to display this Google Drive file',
  BOX_FILE_PREVIEW_ERROR_MESSAGE: 'Unable to display this Box folder',
  CONTENT_DELETE_ERROR_GD_MESSAGE: 'Google Drive is no longer available in Good & Co Inc.',
  BROWSE_FILES_LABEL: 'browse files',
  SNOW_SUCCESS_MESSAGE: 'Connected to Servicenow successfully',
  SNOW_TICKET_CREATION_MESSAGE: 'Created new ServiceNow ticket successfully',
  SNOW_DISCONNECT_MESSAGE: 'Disconnected ServiceNow successfully',
  CONFLUENCE_SUCCESS_MESSAGE: 'Connected to Atlassian Confluence successfully',
  CONFLUENCE_DOMAIN_ERROR_MESSAGE:
    'Connection failed - Domain/site must match with one used to connect Confluence service account',
  NON_WHITELISTED_DOMAIN_CONNECTION_FAIL_MESSAGE:
    'Connection failed - User account does not belong to the domain that has been setup by the app manager',
  OUTLOOK_CONNECT_SUCCESS_MESSAGE: 'Connected to Microsoft Outlook Calendar successfully',
  EMPTY_OUTLOOK_CALENDAR_GROUP_MESSAGE: 'No calendar is available for the selected group',
  INCORRECT_FORMAT_VALIDATION_MESSAGE: 'Unexpected token \'i\', "incorrect format" is not valid JSON',
  REQUESTED_TIME_OFF_SUCCESSFULLY_MESSAGE: 'Requested time off successfully',
  REQUESTED_TIME_OFF_LABEL: 'Requested time off',
  RESPONSE_SAVED_MESSAGE: 'Your RSVP response has been saved',
  LEAVE_REQUEST_SUCCESSFULLY_MESSAGE: 'Requested leave of absence successfully',
  OKTA_GROUP_WRONG_CONNECTION: 'Incorrect credentials. Please try again.',
  NO_GROUP_SELECTED_MESSAGE: 'Please select at least one Microsoft Entra ID group',
  OKTA_NO_GROUP_SELECTED_MESSAGE: 'Please select at least one Okta group',
  getAppAddedMessage: (appName: string) => `${appName} added`,
  getAppDeletedMessage: (appName: string) => `${appName} deleted`,
  getAppEnabledMessage: (appName: string) => `${appName} enabled`,
  getAppDisabledMessage: (appName: string) => `${appName} disabled`,
  getAppConnectedMessage: (appName: string) => `Connected to ${appName} successfully`,
  getAppDisconnectedMessage: (appName: string) => `${appName} disconnected`,
  getAppDisconnectingConfirmationMessage: (appName: string) =>
    `Are you sure you want to disconnect the ${appName} account?`,
  getAppConnectionUnavailableMessage: (appName: string) =>
    `${appName} connection is currently unavailable. Contact your app manager.`,

  getAppDisconnectingConfirmationMessageHomeAndSiteDashboardTiles: `Home and site dashboard tiles using this connection will be removed`,
  VALID_URL: 'This is not a valid URL',
  MISSING_FIELD: 'Please fill out this field',
  getAppPublishedMessage: (appName: string) => `${appName} published`,
  NO_RESULTS_TEXT: 'No results Try adjusting search term or filters',
  TILE_SAVED_DRAFT: 'Tile saved as draft',
  TILE_PUBLISHED: 'Tile published',
  API_ACTION_EXECUTED: 'API action executed',
  ADD_TILE_SUCCESS: 'addTileSuccessMessage',
  INCOMPLETE_SUCCESS_SETTINGS: 'Incomplete success settings',
  INCOMPLETE_ERROR_SETTINGS: 'Incomplete error settings',
  SAVE_TILE_FAILED: 'Save tile failed',
  TILE_CANNOT_BE_EMPTY: 'Tile cannot be empty',
  CHANGE_TILE_TYPE: 'Change tile type',
  CHANGE_TILE_TYPE_MESSAGE:
    'Changing the tile type will reset the current canvas configuration. Do you want to continue?',
} as const;
