export const MonthlyReportsSql = {
  /**
   * Monthly Reports Adoption Dashboard Query
   * Returns monthly adoption metrics with month end snapshots and current data
   */
  MONTHLY_REPORTS_ADOPTION: `
SELECT
  COALESCE(
    CONCAT(MONTHNAME(COALESCE(ul.REPORTING_MONTH, adp.REPORTING_MONTH)), ' ', YEAR(COALESCE(ul.REPORTING_MONTH, adp.REPORTING_MONTH))),
    ''
  ) AS Month,
  COALESCE(ul.TOTAL_ACTIVE_USERS, 0) AS Total_active_users,   -- from monthly snapshot
  COALESCE(ul.USER_LOGGED_IN, 0) AS User_logged_in_count,
  COALESCE(ul.USER_LOGGED_IN_PERCENTAGE, 0) AS User_logged_in_percentage,
  COALESCE(adp.TOTAL_USER, 0) AS Total_users_as_of_today,     -- 👈 month-wise from VW_USER_AS_IS
  COALESCE(adp.ACTIVE_USER_ADOPTION, 0) AS Active_user_adoption_count,
  COALESCE(adp.ACTIVE_USER_ADOPTION_PERCENTAGE, 0) AS Active_user_adoption_percentage,
  COALESCE(ul.VIEWED_CONTENT, 0) AS Viewed_content_count,
  COALESCE(ul.VIEWED_CONTENT_PERCENTAGE, 0) AS Viewed_content_percentage,
  COALESCE(ul.AVG_VIEW_PER_USER, 0) AS AVG_VIEW_PER_USER,
  COALESCE(ul.POSTS_AND_REPLIES, 0) AS POSTS_AND_REPLIES,
  COALESCE(ul.LIKES, 0) AS LIKES,
  COALESCE(ul.SHARES, 0) AS SHARES
FROM (
  SELECT
    REPORTING_MONTH,
    UNIQUE_LOGINS_OVERALL AS USER_LOGGED_IN,
    TOTAL_ACTIVE_USERS,
    CASE
      WHEN TOTAL_ACTIVE_USERS = 0 THEN 0
      ELSE ROUND(UNIQUE_LOGINS_OVERALL / TOTAL_ACTIVE_USERS * 100)
    END AS USER_LOGGED_IN_PERCENTAGE,
    TOTAL_CONTENT_VIEWS_OVERALL AS VIEWED_CONTENT,
    CASE
      WHEN TOTAL_ACTIVE_USERS = 0 THEN 0
      ELSE ROUND(USERS_VIEWED_CONTENT / TOTAL_ACTIVE_USERS * 100)
    END AS VIEWED_CONTENT_PERCENTAGE,
    CASE
      WHEN TOTAL_ACTIVE_USERS = 0 THEN 0
      ELSE ROUND(TOTAL_CONTENT_VIEWS_OVERALL / TOTAL_ACTIVE_USERS, 1)
    END AS AVG_VIEW_PER_USER,
    TOTAL_POSTS + TOTAL_REPLIES + TOTAL_COMMENTS AS POSTS_AND_REPLIES,
    TOTAL_LIKES AS LIKES,
    TOTAL_SHARES AS SHARES
  FROM "SIMPPLR_COMMON_TENANT"."UDL"."MONTHLY_TENANT_ADOPTION_SNAPSHOT"
  WHERE TENANT_CODE = '{tenantCode}'
) ul
FULL JOIN (
  SELECT
    DATE_TRUNC('MONTH', ua.REPORTING_DATE)::DATE AS REPORTING_MONTH,
    COUNT(DISTINCT CASE WHEN has_logged_in = TRUE THEN ua.USER_CODE END) AS ACTIVE_USER_ADOPTION,
    COUNT(DISTINCT ua.USER_CODE) AS TOTAL_USER,   -- 👈 month-wise total users
    ROUND(
      COUNT(DISTINCT CASE WHEN has_logged_in = TRUE THEN ua.USER_CODE END)::decimal
      / NULLIF(COUNT(DISTINCT ua.USER_CODE), 0) * 100, 0
    ) AS ACTIVE_USER_ADOPTION_PERCENTAGE
  FROM "SIMPPLR_COMMON_TENANT"."UDL"."VW_DAILY_USER_ADOPTION" ua
  JOIN "SIMPPLR_COMMON_TENANT"."UDL"."VW_USER_AS_IS" us
    ON ua.USER_CODE = us.CODE
  WHERE ua.TENANT_CODE = '{tenantCode}'
    AND status_code = 'US001'
  GROUP BY DATE_TRUNC('MONTH', ua.REPORTING_DATE)
) adp
ON ul.REPORTING_MONTH = adp.REPORTING_MONTH
WHERE COALESCE(ul.REPORTING_MONTH, adp.REPORTING_MONTH)::DATE >= CURRENT_DATE() - 1110
ORDER BY COALESCE(ul.REPORTING_MONTH, adp.REPORTING_MONTH) DESC
LIMIT 36;
  `,
};
