export enum TestSuite {
  CHAT = '@chat',
  GLOBAL_SEARCH = '@global-search',
  ENTERPRISE_SEARCH = '@enterprise-search',
  SITE_SEARCH = '@site-search',
  CHAT_ATTACHMENT = '@chat-attachment',
  CHAT_DIRECT = '@direct-chat',
  CHAT_GROUP = '@group-chat',
  FOOTER = '@footer',
  LINK_TILE_SEARCH = '@link-tile-search',
  APPS_SEARCH = '@apps-search',
  ABAC = '@abac',
  AUDIENCE = '@audience',
  AUDIENCE_CATEGORY = '@audience-category',
  AUDIENCE_CSV = '@audience-csv',
}
