import { expect, Locator, Page } from '@playwright/test';

import { TIMEOUTS } from '@core/constants/timeouts';
import { BasePage } from '@core/pages/basePage';

import { PAGE_ENDPOINTS } from '../../../core/constants/pageEndpoints';

export class ManageQRPage extends BasePage {
  readonly manageLink: Locator;
  readonly qrCodesLink: Locator;
  readonly addQRButton: Locator;
  readonly appPromotionLink: Locator;
  readonly eyeIcon: Locator;
  readonly saveAndVisitDashboardBtn: Locator;
  readonly qrNameField: Locator;
  readonly description: Locator;
  readonly promoteMobileAppPage: Locator;
  readonly manageQRPageHeading: Locator;
  readonly toggleOnQRName: Locator;
  readonly togglePopup: Locator;
  readonly imageQROnPreview: Locator;
  readonly descriptionOfQROnPreview: Locator;
  readonly appPreviewQRPopupHeader: Locator;
  readonly deleteQR: Locator;

  constructor(page: Page) {
    super(page, PAGE_ENDPOINTS.MANAGE_QR_PAGE);
    this.manageLink = page.getByRole('menuitem', { name: 'Manage features', exact: true });
    this.qrCodesLink = page.getByRole('menuitem', { name: 'QR codes QR codes' });
    this.addQRButton = page.getByText('Add QR');
    this.appPromotionLink = page.getByText('App promotionActive');
    this.eyeIcon = page.getByTestId('preview-button');
    this.saveAndVisitDashboardBtn = page.getByRole('button', { name: 'Save and visit dashboard' });
    this.qrNameField = page.getByRole('textbox', { name: 'QR name*' });
    this.description = page.getByTestId('tiptap-content').getByRole('paragraph');
    this.promoteMobileAppPage = page.getByText('Promote mobile app via QR');
    this.manageQRPageHeading = page.getByText('Manage QR');
    this.toggleOnQRName = page.getByRole('button', { name: 'Toggle' });
    this.togglePopup = page.getByRole('tooltip');
    this.imageQROnPreview = page.getByRole('img', { name: "You're previewing the QR code" }).first();
    this.descriptionOfQROnPreview = page.getByText('This is getting generated by automation').first();
    this.appPreviewQRPopupHeader = page.getByText('Promote mobile app via QR');
    this.deleteQR = page.getByRole('menuitem', { name: 'Delete' });
  }

  async verifyThePageIsLoaded(): Promise<void> {
    await this.verifier.verifyTheElementIsVisible(this.manageLink, {
      assertionMessage: 'Verify the manage link is visible',
      timeout: TIMEOUTS.MEDIUM,
    });
  }

  async clickOnManage() {
    await this.clickOnElement(this.manageLink, { stepInfo: 'Click on manage link button' });
  }

  async clickOnQRCodesMenu() {
    await this.clickOnElement(this.qrCodesLink, { stepInfo: 'Click on QR codes menu' });
  }

  async clickOnAddQR() {
    await this.clickOnElement(this.addQRButton, { stepInfo: 'Click on Add QR button' });
  }

  async clickOnAppPromotion() {
    await this.clickOnElement(this.appPromotionLink, { stepInfo: 'Click on app promotion link', force: true });
  }

  async clickEyeIcon() {
    await this.clickOnElement(this.eyeIcon, { stepInfo: 'Click on eye icon for preview' });
  }

  async clickSaveAndVisit() {
    await this.clickOnElement(this.saveAndVisitDashboardBtn, { stepInfo: 'Click on save and visit dashboard button' });
  }

  async fillQRName(qrName = 'generated by automation') {
    await this.fillInElement(this.qrNameField, qrName, { stepInfo: 'Fill QR name' });
  }

  async fillDescription(description = 'This is getting generated by automation') {
    await this.fillInElement(this.description, description, { stepInfo: 'Fill QR description' });
  }

  async verifyPromoteMobileAppPageHeading() {
    await this.verifier.verifyElementHasText(this.promoteMobileAppPage, 'Promote mobile app via QR');
  }

  async verifyManagePage() {
    await this.verifier.verifyElementHasText(this.manageQRPageHeading, 'Manage QR');
  }

  async verifyQRName(qrName = 'generated by automation') {
    const qrNameLocator = this.page.locator('h4', { hasText: qrName.trim() }).first();
    await this.verifier.verifyTheElementIsVisible(qrNameLocator, {
      assertionMessage: `Verify QR name "${qrName}" is visible`,
    });
  }

  async verifyPopupDisplayedByHeader(popupTitle: string) {
    await expect(this.appPreviewQRPopupHeader).toBeVisible();
  }

  async verifyQRImageDisplayOnPreview() {
    await expect(this.imageQROnPreview).toBeVisible();
  }

  async verifyQRDescriptionOnPreview() {
    await expect(this.descriptionOfQROnPreview).toHaveText('This is getting generated by automation');
  }

  async clickOnThreeDots() {
    const threeDotsButton = this.page
      .locator('tr')
      .filter({ hasText: 'generated by automation' })
      .nth(0)
      .locator('button[aria-label="More options"]');
    await this.clickOnElement(threeDotsButton, { stepInfo: 'Click on three dots menu' });
  }

  async clickOnDelete() {
    await this.clickOnElement(this.deleteQR, { stepInfo: 'Click on delete menu item' });
  }

  async clickOnDeleteButton() {
    const deleteButton = this.page.locator('[role="dialog"]').getByRole('button', { name: 'Delete' });
    await this.clickOnElement(deleteButton, { stepInfo: 'Click on delete button in confirmation dialog' });
  }

  async deleteAppQR() {
    await this.clickOnThreeDots();
    await this.clickOnDelete();
    await this.clickOnDeleteButton();
  }
}
