export enum LANGUAGE_CODES {
  ENGLISH_US = 'en-US',
  ENGLISH_GB = 'en-GB',
  FRENCH_FR = 'fr-FR',
  SPANISH_ES = 'es-ES',
  GERMAN_DE = 'de-DE',
  ITALIAN_IT = 'it-IT',
  JAPANESE_JP = 'ja-JP',
  PORTUGUESE_BR = 'pt-BR',
  CHINESE_CN = 'zh-CN',
  DUTCH_NL = 'nl-NL',
  ROMANIAN_RO = 'ro-RO',
  ARMENIAN_AM = 'hy-AM',
  BULGARIAN_BG = 'bg-BG',
  DANISH_DA = 'da-DA',
  MALAY_MY = 'ms-MY',
  THAI_TH = 'th-TH',
}

// array of values for iteration/exports
export const LANGUAGE_CODE_VALUES = [
  LANGUAGE_CODES.ENGLISH_US,
  LANGUAGE_CODES.ENGLISH_GB,
  LANGUAGE_CODES.FRENCH_FR,
  LANGUAGE_CODES.SPANISH_ES,
  LANGUAGE_CODES.GERMAN_DE,
  LANGUAGE_CODES.ITALIAN_IT,
  LANGUAGE_CODES.JAPANESE_JP,
  LANGUAGE_CODES.PORTUGUESE_BR,
  LANGUAGE_CODES.CHINESE_CN,
  LANGUAGE_CODES.DUTCH_NL,
  LANGUAGE_CODES.ROMANIAN_RO,
  LANGUAGE_CODES.ARMENIAN_AM,
  LANGUAGE_CODES.BULGARIAN_BG,
  LANGUAGE_CODES.DANISH_DA,
  LANGUAGE_CODES.MALAY_MY,
  LANGUAGE_CODES.THAI_TH,
] as const;

export type LanguageCode = (typeof LANGUAGE_CODE_VALUES)[number];

// Default export for easy importing
export default LANGUAGE_CODE_VALUES;
