export enum ContentTestSuite {
  PAGE_APP_MANAGER = '@page-app-manager',
  PAGE_STANDARD_USER = '@page-standard-user',
  ALBUM_APP_MANAGER = '@album-app-manager',
  ALBUM_STANDARD_USER = '@album-standard-user',
  EVENT_APP_MANAGER = '@event-app-manager',
  EVENT_STANDARD_USER = '@event-standard-user',
  FEED_APP_MANAGER = '@feed-app-manager',
  FEED_MENTION_SITE_TOPIC_USER_APP_MANAGER = '@feed-mention-site-topic-user-app-manager',
  FEED_FILE_DELETE_APP_MANAGER = '@feed-file-delete-app-manager',
  FEED_MULTI_USER = '@feed-multi-user',
  FEED_STANDARD_USER = '@feed-standard-user',
  SITE_APP_MANAGER = '@site-app-manager',
  ATTACHMENTS = '@attachments',
  FEATURED_SITES = '@featured-sites',
  FEED_COMMENT_MENTION_NOTIFICATION = '@feed-comment-mention-notification',
  FEED_IMAGE_UPDATE_APP_MANAGER = '@feed-image-update-app-manager',
  FILES_PREVIEW = '@Files-Preview',
  FEED_REPLY_APP_MANAGER = '@feed-reply-app-manager',
  ADD_CONTENT_ON_UNLISTED_SITE = '@add-content-on-unlisted-site',
  Q_AND_A = '@q-and-a',
  SOCIAL_CAMPAIGN = '@social-campaign',
}
