export enum ContentSuiteTags {
  CONTENT_MANAGEMENT = '@content-management',
  PAGE_CREATION = '@page-creation',
  CONTENT_UPLOAD = '@content-upload',
  ALBUM = '@album',
  SITE_DASHBOARD = '@site-dashboard',
  SITE_CREATION = '@site-creation',
}

export enum ContentFeatureTags {
  COVER_IMAGE = '@cover-image',
  ALBUM_CREATION = '@album-creation',
  ALBUM_FILTERING = '@album-filtering',
  ALBUM_ATTACHMENTS = '@album-attachments',
  ALBUM_HISTORY = '@album-history',
  ALBUM_DOWNLOAD = '@album-download',
  ALBUM_VIDEO = '@album-video',
  ALBUM_COUNT = '@album-count',
  ALBUM_VIDEO_EDIT = '@album-video-edit',
  ALBUM_EDIT_CANCEL = '@album-edit-cancel',
  ALBUM_UNPUBLISH = '@album-unpublish',
  ALBUM_LONG_TITLE = '@album-long-title',
  ALBUM_FILE_ATTACHMENT = '@album-file-attachment',
  ALBUM_COVER_IMAGE = '@album-cover-image',
  ALBUM_FEED_POST = '@album-feed-post',
  ALBUM_CONTENT_TAB = '@album-content-tab',
  ALBUM_UNPUBLISH_FUNCTIONALITY = '@album-unpublish-functionality',
  ALBUM_DELETE_FUNCTIONALITY = '@album-delete-functionality',
  ALBUM_LIKE_FUNCTIONALITY = '@album-like-functionality',
  ALBUM_HASHTAG_TOPIC = '@album-hashtag-topic',
  ALBUM_MOVE_CONTENT = '@album-move-content',
  ALBUM_MOVE_PRIVATE_TO_PUBLIC = '@album-move-private-to-public',
  ALBUM_OPEN_ALBUM_PRIVATE_SITE = '@album-open-album-private-site',
  ALBUM_DELETE_CONTENT_PAGE = '@album-delete-content-page',
  ALBUM_FILTER_BY_AUTHOR = '@album-filter-by-author',
  ALBUM_EMAIL_NOTIFICATIONS = '@album-email-notifications',
  ALBUM_CONCURRENT_EDITING = '@album-concurrent-editing',
  ALBUM_SITE_OWNER_EDITING_CONFLICT = '@album-site-owner-editing-conflict',
  ALBUM_SEQUENTIAL_EDITING = '@album-sequential-editing',
  ALBUM_YOUTUBE_VIDEO_COVER = '@album-youtube-video-cover',
  ALBUM_NON_MEMBER_ADD_IMAGES = '@album-non-member-add-images',
  ALBUM_DELETED_LINK_ACCESS = '@album-deleted-link-access',
  ALBUM_DRAFT_SAVE = '@album-draft-save',
  ALBUM_REQUIRED_TITLE_VALIDATION = '@album-required-title-validation',
  ALBUM_FUTURE_PUBLISH_DATE = '@album-future-publish-date',
  ALBUM_PUBLISH_UNTIL_DATE = '@album-publish-until-date',
}

export const ContentTestTags = [...Object.values(ContentSuiteTags), ...Object.values(ContentFeatureTags)] as const;

export default ContentTestTags;
