import { expect } from '@playwright/test';
import { rewardTestFixture as test } from '@rewards/fixtures/rewardFixture';
import { RewardsStore } from '@rewards-pages/reward-store/reward-store';
import { UserProfilePage } from '@rewards-pages/user-profile/user-profile-page';

import { TestPriority } from '@core/constants/testPriority';
import { TestGroupType } from '@core/constants/testType';
import { tagTest } from '@core/utils/testDecorator';
import { REWARD_FEATURE_TAGS, REWARD_SUITE_TAGS } from '@modules/reward/constants/testTags';

test.describe('rewards store', { tag: [REWARD_SUITE_TAGS.REWARD_STORE] }, () => {
  test.beforeEach(async ({ appManagerFixture }) => {
    const rewardsStore = new RewardsStore(appManagerFixture.page);
    await rewardsStore.enableTheRewardStoreAndPeerGiftingIfDisabled();
  });
  test(
    '[RC-3311] Validate if Categories option list on rewards store page is showing in Users set language',
    {
      tag: [REWARD_FEATURE_TAGS.REWARD_STORE, TestGroupType.REGRESSION, TestPriority.P0, TestGroupType.SMOKE],
    },
    async ({ appManagerFixture }) => {
      tagTest(test.info(), {
        description: 'Validate if Categories option list on rewards store page is showing in Users set language',
        zephyrTestId: 'RC-3311',
        storyId: 'RC-3311',
      });
      const rewardsStore = new RewardsStore(appManagerFixture.page);
      const userProfile = new UserProfilePage(appManagerFixture.page);

      // Open the Reward, and select the United States as a country
      await rewardsStore.selectCountry('United States');

      // Get All the categories in English language and validate
      const categories = [
        'All categories',
        'Auto Care',
        'Beauty',
        'Beverage',
        'Digital Media',
        'Dining',
        'Entertainment',
        'Fashion',
        'For the Home',
        'Fuel',
        'Gaming',
        'Grocery',
        'Health & Wellness',
        'Kids & Baby',
        'Marketplaces & Department Stores',
        'Pet Care',
        'Self Care',
        'Specialty',
        'Sporting Goods',
        'Technology',
        'Travel',
      ];
      let categoriesOnUi = await rewardsStore.getAllCategories();
      console.log('UI:' + categoriesOnUi);
      console.log('API:' + categories);
      expect(categoriesOnUi).toEqual(categories);

      // Set the Language as "French", Get All the categories in French language and validate
      await userProfile.mockAppConfigLanguage(rewardsStore.page, 3);
      await rewardsStore.verifyThePageIsLoaded();
      const frenchCategories = [
        'Toutes les catégories',
        'Articles de sport',
        'Beauté',
        'Boissons',
        'Carburant',
        'Divertissement',
        'Enfants et bébés',
        'Entretien automobile',
        'Épicerie',
        'Jeux',
        'Marchés et grands magasins',
        'Médias numériques',
        'Mode',
        'Pour la maison',
        'Prendre soin de soi',
        'Restauration',
        'Santé et bien-être',
        'Soins pour animaux de compagnie',
        'Spécialité',
        'Technologie',
        'Voyage',
      ];
      categoriesOnUi = await rewardsStore.getAllCategories();
      console.log('UI:' + categoriesOnUi);
      console.log('API:' + frenchCategories);
      expect(categoriesOnUi).toEqual(frenchCategories);
      await userProfile.restoreAppConfigMock(rewardsStore.page);

      // Set the Language as "German", Get All the categories in German language and validate
      await userProfile.mockAppConfigLanguage(rewardsStore.page, 6);
      await rewardsStore.verifyThePageIsLoaded();
      const germanCategories = [
        'Alle Kategorien',
        'Autopflege',
        'Digitale Medien',
        'Für Zuhause',
        'Gesundheit und Wellness',
        'Getränke',
        'Haustierpflege',
        'Kinder und Baby',
        'Kraftstoff',
        'Lebensmittel',
        'Marktplätze und Kaufhäuser',
        'Mode',
        'Reise',
        'Schönheit',
        'Selbstpflege',
        'Speisen',
        'Spezialität',
        'Spielen',
        'Sportartikel',
        'Technologie',
        'Unterhaltung',
      ];
      categoriesOnUi = await rewardsStore.getAllCategories();
      console.log('UI:' + categoriesOnUi);
      console.log('API:' + germanCategories);
      expect(categoriesOnUi).toEqual(germanCategories);
      await userProfile.restoreAppConfigMock(rewardsStore.page);
    }
  );

  test(
    "[RC-3312] Validate if location list on rewards store page is showing in User's set language",
    {
      tag: [REWARD_FEATURE_TAGS.REWARD_STORE, TestGroupType.REGRESSION, TestPriority.P0, TestGroupType.SMOKE],
    },
    async ({ appManagerFixture }) => {
      tagTest(test.info(), {
        description: "Validate if location list on rewards store page is showing in User's set language",
        zephyrTestId: 'RC-3312',
        storyId: 'RC-3312',
      });
      const rewardsStore = new RewardsStore(appManagerFixture.page);
      const userProfile = new UserProfilePage(appManagerFixture.page);

      // Open the Reward, and select the United States as a country
      await rewardsStore.selectCountry('United States');

      // Set the Language as "French", Get All the countries in French language and validate
      await userProfile.mockAppConfigLanguage(rewardsStore.page, 3);
      await rewardsStore.verifyThePageIsLoaded();
      const frenchCountries = [
        'Afghanistan',
        'Îles Åland',
        'Albanie',
        'Algérie',
        'Samoa américaines',
        'Andorre',
        'Angola',
        'Anguilla',
        'Antarctique',
        'Antigua et Barbuda',
        'Argentine',
        'Arménie',
        'Aruba',
        'Australie',
        'Autriche',
        'Azerbaïdjan',
        'Bahamas',
        'Bahreïn',
        'Bangladesh',
        'Barbade',
        'Biélorussie',
        'Belgique',
        'Belize',
        'Bénin',
        'Bermudes',
        'Bhoutan',
        'Bolivie',
        'Bonaire',
        'Bosnie-Herzégovine',
        'Botswana',
        'Île Bouvet',
        'Brésil',
        "Territoire britannique de l'océan Indien",
        'Brunei Darussalam',
        'Bulgarie',
        'Burkina Faso',
        'Burundi',
        'Cabo Verde',
        'Cambodge',
        'Cameroun',
        'Canada',
        'Îles Caïmans',
        'République centrafricaine',
        'Tchad',
        'Chili',
        'Chine',
        'Île Christmas',
        'Îles Cocos',
        'Colombie',
        'Comores',
        'Congo',
        'République démocratique du Congo',
        'Îles Cook',
        'Costa Rica',
        'Côte d’Ivoire',
        'Croatie',
        'Curaçao',
        'Chypre',
        'Tchéquie',
        'Danemark',
        'Djibouti',
        'Dominique',
        'République dominicaine',
        'Équateur',
        'Égypte',
        'Salvador',
        'Guinée équatoriale',
        'Érythrée',
        'Estonie',
        'Éthiopie',
        'Îles Falkland',
        'Îles Féroé',
        'Fidji',
        'Finlande',
        'France',
        'Guyane française',
        'Polynésie française',
        'Terres australes françaises',
        'Gabon',
        'Gambie',
        'Géorgie',
        'Allemagne',
        'Ghana',
        'Gibraltar',
        'Grèce',
        'Groenland',
        'Grenade',
        'Guadeloupe',
        'Guam',
        'Guatemala',
        'Guernesey',
        'Guinée',
        'Guinée-Bissau',
        'Guyane',
        'Haïti',
        'Îles Heard-et-MacDonald',
        'Saint-Siège',
        'Honduras',
        'Hong Kong',
        'Hongrie',
        'Islande',
        'Inde',
        'Indonésie',
        'Irak',
        'Irlande',
        'Île de Man',
        'Israël',
        'Italie',
        'Jamaïque',
        'Japon',
        'Jersey',
        'Jordan',
        'Kazakhstan',
        'Kenya',
        'Kiribati',
        'Corée du Sud',
        'Koweït',
        'Kirghizistan',
        'République démocratique populaire du Laos',
        'Lettonie',
        'Liban',
        'Lesotho',
        'Libéria',
        'Libye',
        'Liechtenstein',
        'Lituanie',
        'Luxembourg',
        'Macao',
        'Macédoine du Nord',
        'Madagascar',
        'Malawi',
        'Malaisie',
        'Maldives',
        'Mali',
        'Malte',
        'Îles Marshall',
        'Martinique',
        'Mauritanie',
        'Maurice',
        'Mayotte',
        'Mexique',
        'Micronésie',
        'Moldova',
        'Monaco',
        'Mongolie',
        'Monténégro',
        'Montserrat',
        'Maroc',
        'Mozambique',
        'Namibie',
        'Nauru',
        'Népal',
        'Pays-Bas',
        'Nouvelle-Calédonie',
        'Nouvelle-Zélande',
        'Nicaragua',
        'Niger',
        'Nigéria',
        'Nioué',
        'Île Norfolk',
        'Îles Mariannes du Nord',
        'Norvège',
        'Oman',
        'Pakistan',
        'Palaos',
        'Palestine',
        'Panama',
        'Papouasie-Nouvelle-Guinée',
        'Paraguay',
        'Pérou',
        'Philippines',
        'Pitcairn',
        'Pologne',
        'Portugal',
        'Porto Rico',
        'Qatar',
        'Réunion',
        'Roumanie',
        'Rwanda',
        'Saint-Barthélemy',
        'Sainte-Hélène',
        'Saint-Christophe-et-Niévès',
        'Sainte Lucie',
        'Saint-Martin',
        'Saint-Pierre-et-Miquelon',
        'Saint-Vincent-et-les-Grenadines',
        'Samoa',
        'Saint-Marin',
        'Sao Tomé-et-Principe',
        'Arabie Saoudite',
        'Sénégal',
        'Serbie',
        'Seychelles',
        'Sierra Leone',
        'Singapour',
        'Saint-Martin',
        'Slovaquie',
        'Slovénie',
        'Îles Salomon',
        'Somalie',
        'Afrique du Sud',
        'Géorgie du Sud et les îles Sandwich du Sud',
        'Soudan du Sud',
        'Espagne',
        'Sri Lanka',
        'Soudan',
        'Suriname',
        'Svalbard et Jan Mayen',
        'Eswatini',
        'Suède',
        'Suisse',
        'Taïwan',
        'Tadjikistan',
        'Tanzanie',
        'Thaïlande',
        'Timor-Leste',
        'Togo',
        'Tokélaou',
        'Tonga',
        'Trinité-et-Tobago',
        'Tunisie',
        'Turquie',
        'Turkménistan',
        'Îles Turques-et-Caïques',
        'Tuvalu',
        'Ouganda',
        'Émirats arabes unis',
        'Royaume-Uni',
        'États-Unis',
        'Îles mineures éloignées des États-Unis',
        'Uruguay',
        'Ouzbékistan',
        'Vanuatu',
        'Viêt Nam',
        'Îles Vierges britanniques',
        'Îles Vierges (États-Unis)',
        'Wallis et Futuna',
        'Sahara occidental',
        'Yémen',
        'Zambie',
      ];
      let countriesOnUi = await rewardsStore.getAllCountries();
      console.log('UI:' + countriesOnUi);
      console.log('API:' + frenchCountries);
      expect(countriesOnUi).toEqual(frenchCountries);
      await userProfile.restoreAppConfigMock(rewardsStore.page);

      // Set the Language as "German", Get All the countries in German language and validate
      await userProfile.mockAppConfigLanguage(rewardsStore.page, 6);
      await rewardsStore.verifyThePageIsLoaded();
      const germanCountries = [
        'Afghanistan',
        'Åland Inseln',
        'Albanien',
        'Algerien',
        'Amerikanisch-Samoa',
        'Andorra',
        'Angola',
        'Anguilla',
        'Antarktis',
        'Antigua und Barbuda',
        'Argentinien',
        'Armenien',
        'Aruba',
        'Australien',
        'Österreich',
        'Aserbaidschan',
        'Bahamas',
        'Bahrain',
        'Bangladesch',
        'Barbados',
        'Belarus',
        'Belgien',
        'Belize',
        'Benin',
        'Bermuda',
        'Bhutan',
        'Bolivien',
        'Bonaire',
        'Bosnien und Herzegowina',
        'Botsuana',
        'Bouvetinsel',
        'Brasilien',
        'Britisches Territorium im Indischen Ozean',
        'Brunei Darussalam',
        'Bulgarien',
        'Burkina Faso',
        'Burundi',
        'Cabo Verde',
        'Kambodscha',
        'Kamerun',
        'Kanada',
        'Kaimaninseln',
        'Zentralafrikanische Republik',
        'Tschad',
        'Chile',
        'China',
        'Weihnachtsinsel',
        'Kokosinseln',
        'Kolumbien',
        'Komoren',
        'Demokratische Republik Kongo',
        'Demokratische Republik Kongo',
        'Cookinseln',
        'Costa Rica',
        "Côte d'Ivoire",
        'Kroatien',
        'Curaçao',
        'Zypern',
        'Tschechien',
        'Dänemark',
        'Dschibuti',
        'Dominica',
        'Dominikanische Republik',
        'Ecuador',
        'Ägypten',
        'El Salvador',
        'Äquatorialguinea',
        'Eritrea',
        'Estland',
        'Äthiopien',
        'Falklandinseln',
        'Färöer',
        'Fidschi',
        'Finnland',
        'Frankreich',
        'Französisch-Guayana',
        'Französisch-Polynesien',
        'Französische Gebiete im südlichen Indischen Ozean',
        'Gabun',
        'Gambia',
        'Georgien',
        'Deutschland',
        'Ghana',
        'Gibraltar',
        'Griechenland',
        'Grönland',
        'Grenada',
        'Guadeloupe',
        'Guam',
        'Guatemala',
        'Guernsey',
        'Guinea',
        'Guinea-Bissau',
        'Guyana',
        'Haiti',
        'Heard und McDonaldinseln',
        'Heiliger Stuhl',
        'Honduras',
        'Hongkong',
        'Ungarn',
        'Island',
        'Indien',
        'Indonesien',
        'Irak',
        'Irland',
        'Insel Man',
        'Israel',
        'Italien',
        'Jamaika',
        'Japan',
        'Jersey',
        'Jordanien',
        'Kasachstan',
        'Kenia',
        'Kiribati',
        'Südkorea',
        'Kuwait',
        'Kirgisistan',
        'Demokratische Volksrepublik Laos',
        'Lettland',
        'Libanon',
        'Lesotho',
        'Liberia',
        'Libyen',
        'Liechtenstein',
        'Litauen',
        'Luxemburg',
        'Macau',
        'Nordmazedonien',
        'Madagaskar',
        'Malawi',
        'Malaysia',
        'Malediven',
        'Mali',
        'Malta',
        'Marshallinseln',
        'Martinique',
        'Mauretanien',
        'Mauritius',
        'Mayotte',
        'Mexiko',
        'Mikronesien',
        'Republik Moldau',
        'Monaco',
        'Mongolei',
        'Montenegro',
        'Montserrat',
        'Marokko',
        'Mosambik',
        'Namibia',
        'Nauru',
        'Nepal',
        'Niederlande',
        'Neukaledonien',
        'Neuseeland',
        'Nicaragua',
        'Niger',
        'Nigeria',
        'Niue',
        'Norfolkinsel',
        'Nördliche Marianen',
        'Norwegen',
        'Oman',
        'Pakistan',
        'Palau',
        'Palästina',
        'Panama',
        'Papua-Neuguinea',
        'Paraguay',
        'Peru',
        'Philippinen',
        'Pitcairn',
        'Polen',
        'Portugal',
        'Puerto Rico',
        'Katar',
        'Réunion',
        'Rumänien',
        'Ruanda',
        'St. Barthélemy',
        'St. Helena',
        'St. Kitts und Nevis',
        'St. Lucia',
        'St. Martin',
        'St. Pierre und Miquelon',
        'St. Vincent und die Grenadinen',
        'Samoa',
        'San Marino',
        'São Tomé und Príncipe',
        'Saudi-Arabien',
        'Senegal',
        'Serbien',
        'Seychellen',
        'Sierra Leone',
        'Singapur',
        'St. Maarten',
        'Slowakische Republik',
        'Slowenien',
        'Salomonen',
        'Somalia',
        'Südafrika',
        'Südgeorgien und Südliche Sandwichinseln',
        'Südsudan',
        'Spanien',
        'Sri Lanka',
        'Sudan',
        'Surinam',
        'Svalbard und Jan Mayen',
        'Eswantini',
        'Schweden',
        'Schweiz',
        'Taiwan',
        'Tadschikistan',
        'Tansania',
        'Thailand',
        'Timor-Leste',
        'Togo',
        'Tokelau',
        'Tonga',
        'Trinidad und Tobago',
        'Tunesien',
        'Türkei',
        'Turkmenistan',
        'Turks- und Caicosinseln',
        'Tuvalu',
        'Uganda',
        'Vereinigte Arabische Emirate',
        'Großbritannien',
        'Vereinigte Staaten',
        'Kleinere amerikanische Überseeinseln',
        'Uruguay',
        'Usbekistan',
        'Vanuatu',
        'Vietnam',
        'Britische Jungferninseln',
        'Amerikanische Jungferninseln',
        'Wallis und Futuna',
        'Westsahara',
        'Jemen',
        'Sambia',
      ];
      countriesOnUi = await rewardsStore.getAllCountries();
      console.log('UI:' + countriesOnUi);
      console.log('API:' + germanCountries);
      expect(countriesOnUi).toEqual(germanCountries);
      await userProfile.restoreAppConfigMock(rewardsStore.page);
    }
  );
});
