name: UI E2E Tests

on:
  workflow_dispatch: # allows manual triggering of the workflow
    inputs:
      module_name:
        description: 'Select the module to test'
        required: true
        default: 'chat'
        type: choice
        options:
          - 'chat'
          - 'feed'
      priority_filter:
        description: 'Select test cases by priority'
        required: true
        default: '@P0'
        type: choice
        options:
          - '@P0'
          - '@P1'
          - 'all'
      environment:
        description: 'Select the environment to run tests against'
        required: true
        default: 'qa'
        type: choice
        options:
          - 'qa'
          - 'uat'

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  test-and-deploy:
    timeout-minutes: 60
    runs-on: [kubernetes]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run playwright tests
        env:
          TEST_ENV: ${{ inputs.environment || 'qa' }}
        run: |
          if [ "${{ inputs.priority_filter }}" = "all" ]; then
            npm run test:${{ inputs.module_name || 'chat' }}
          else
            npm run test:${{ inputs.module_name || 'chat' }} -- --grep=${{ inputs.priority_filter || '@P0' }}
          fi

      - name: Generate HTML Report
        if: always()
        env:
          TRACE_VIEWER_BASE_URL: https://shiny-adventure-jnkoq9z.pages.github.io/
        run: |
          echo "Using base URL: $TRACE_VIEWER_BASE_URL"
          npm run generate-report:custom test-results/test-results.json

      - name: Prepare deployment content
        if: always()
        run: |
          mkdir -p deploy-content
          cp -rv playwright-report/* deploy-content/
          echo "Final deploy-content structure:"
          find deploy-content -type f

      - name: Upload Pages Artifact
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: deploy-content

      - name: Deploy to GitHub Pages
        if: always()
        id: deployment
        uses: actions/deploy-pages@v4