name: UI E2E Tests

on:
  pull_request:
    branches:
      - main
  workflow_dispatch: # allows manual triggering of the workflow
    inputs:
      module_name:
        description: 'Select the module to test'
        required: true
        default: 'chat'
        type: choice
        options:
          - 'chat'
          - 'feed'
      priority_filter:
        description: 'Select test cases by priority'
        required: true
        default: '@P0'
        type: choice
        options:
          - '@P0'
          - '@P1'

jobs:
  test:
    timeout-minutes: 60
    # use self hosted runner with tag kubernetes
    runs-on: [kubernetes]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: install dependencies
        run: npm ci # install dependencies based on package-lock.json
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run playwright tests
        run: npm run test:${{ inputs.module_name }} -- --grep=${{ inputs.priority_filter }}
      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 2
