name: Prod EU Healthcheck

on:
  schedule:
    # Run daily at 11:30 PM UTC (5:00 AM IST next day)
    - cron: '30 23 * * *'
  workflow_dispatch:

jobs:
  healthcheck:
    uses: ./.github/workflows/prod-healthcheck-template.yml
    with:
      environment: prodEU
      git_ref: main
    secrets: inherit
